### PR TITLE
Fix clipboard for empty browser cache (#1783)

### LINKED ISSUE #1783: Problem: cannot add items to clipboard
### Current Behavior

**Steps to reproduce the behavior**
1. Find any entry
2. Click Add to Clipboard
3. Nothing is added to the clipboard and we can see this error in the console:
  ```
   Uncaught TypeError: this.items is null
   toggle http://localhost:63001/js/clipboard.js:351
   ```

### Expected Behavior

The item should be added to the clipboard...

### Possible Solution

The problem seems to have appeared in this commit: `Fix clipboard storage behaviour (#1749)` (9cf5ac4ea4c31c2b8179d72a812bbfcf634e530d)

### Context and Notes

_No response_

### Version used

AtoM 2.8.1

### Operating System and version

Ubuntu 22.04

### Default installation culture

en

### PHP version

PHP 7.4

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by anvit**
Set browser local storage values for clipboard if their corresponding variables are null on load, which happens if the browser storage is cleared.

### CODE REVIEW

File: js/clipboard.js [hunk 1]
```diff
@@ -18,11 +18,13 @@
...
     {
       this.items = this.initialItems;
+      this.storage.setItem('clipboard', JSON.stringify(this.initialItems));
     }
 
     if (!this.exportTokens)
     {
       this.exportTokens = [];
+      this.storage.setItem('exportTokens', JSON.stringify([]));
     }
```
Comment (jraddaoui) [inline js/clipboard.js]: I'd change the following block:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard'));
    this.exportTokens = JSON.parse(this.storage.getItem('exportTokens'));

    if (!this.items)
    {
      this.items = this.initialItems;
      this.storage.setItem('clipboard', JSON.stringify(this.initialItems));
    }

    if (!this.exportTokens)
    {
      this.exportTokens = [];
      this.storage.setItem('exportTokens', JSON.stringify([]));
    }
```

To this:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard')) || this.initialItems;
    this.exportTokens = JSON.parse(this.storage.getItem('exportTokens')) || [];
```

I know that's just an optimization that won't fix the issue, but then you can do the same inside the toggle functions:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard')) || this.initialItems;
```

I think that's better than writing the default/empty values into localstorage.

**Review by jraddaoui — CHANGES_REQUESTED** [review]
Thanks @anvit!

File: js/clipboard.js (hunk 1 above)
Comment (anvit) [reply js/clipboard.js]: @jraddaoui Makes sense, this makes the code much cleaner! I've updated it, thanks!

File: plugins/arDominionB5Plugin/js/clipboard.js [hunk 2]
```diff
@@ -11,21 +11,13 @@ import Tooltip from "bootstrap/js/dist/tooltip";
 
       this.storage = localStorage;
       this.types = ["informationObject", "actor", "repository"];
-      this.initialItems = JSON.stringify({
+      this.initialItems = {
```
Comment (jraddaoui) [inline plugins/arDominionB5Plugin/js/clipboard.js]: Nitpick: it could go in one line now.

**Review by jraddaoui — APPROVED** [review]
Thanks!

**Comment by jraddaoui** [comment]
Make sure you make Prettier happy ;)
