### PR TITLE
Fix shifted columns in CSV exports

### LINKED ISSUE #2122: Problem: Column mismatches in QubitFlatfileExport
### Current Behavior

**Steps to reproduce the behavior**

1. Run any CSV export, where *only one* column is excluded from the export. A good example is an information object export that excludes the `accessionNumber`

The hidden column is not removed from rows after the second row, so cells in row 2 onward are shifted one column right. The culture column, for example, will appear one column *after* the actual culture heading, like this:

| Row Number | culture |  |
| ---------- | ------- | -- |
| 1 | en | |
| 2 | | en |
| 3 | | en |
| 4 | | en |

`culture` is supposed to be the last column, but an extra "empty" column is created because the column that is supposed to get removed doesn't actually get removed.

This is effectively an off-by-one error. See here:

- One extra element is added:

https://github.com/artefactual/atom/blob/2a5966634063b8e98975ed4c9448ff518e4976c4/lib/flatfile/QubitFlatfileExport.class.php#L111-L112

- The total number of columns - the total number of hidden columns is compared with that number:

https://github.com/artefactual/atom/blob/2a5966634063b8e98975ed4c9448ff518e4976c4/lib/flatfile/QubitFlatfileExport.class.php#L315-L316

Only one column is being hidden, but the `+ 1` that was added to the max columns is "hiding" the fact that this column should be removed.

### Expected Behavior

None of the rows in the CSV should be shifted right.

### Possible Solution

Rather than check the length of the row, a solution is to check if indices of hidden columns are in the row, and remove them if they are.

I can open a PR for this.

### Context and Notes

_No response_

### Version used

AtoM 2.9.2 (Latest qa/2.x)

### Operating System and version

Docker (`php:8.3-fpm-alpine`)

### Default installation culture

en

### PHP version

PHP 8.3

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by danloveg**
Closes #2122 

Fixes the off-by-one error causing columns to be shifted right in flatfile exports.

I've also written some unit tests to run some checks against the `exportResource` logic.

### CODE REVIEW

File: test/phpunit/QubitFlatfileExportTest.php [hunk 1]
```diff
@@ -0,0 +1,302 @@
...
+        $headerData = str_getcsv($rows[0]);
+        $rowData1 = str_getcsv($rows[1]);
+        $rowData2 = str_getcsv($rows[2]);
+        $rowData3 = str_getcsv($rows[3]);
+
+        $this->assertEquals(['colB', 'colC'], $headerData);
+        $this->assertEquals(['B1', 'C1'], $rowData1);
+        $this->assertEquals(['B2', 'C2'], $rowData2);
+        $this->assertEquals(['B3', 'C3'], $rowData3);
+    }
```
Comment (anvit) [inline test/phpunit/QubitFlatfileExportTest.php:336]: It would be good to have a test for exporting multiple resources with multiple hidden columns as well (similar to the single resource one, with columns B and D hidden).

**Review by anvit — COMMENTED** [review]
Thanks so much @danloveg ! I added a comment about one additional test, but other than that this looks good!

File: test/phpunit/QubitFlatfileExportTest.php (hunk 1 above)
Comment (danloveg) [reply test/phpunit/QubitFlatfileExportTest.php:336]: I agree! I also added a test for one hidden column when exporting a single resource. See: https://github.com/artefactual/atom/pull/2123/commits/581d6d64a741822dbabd363552bd2e7822dcaa22

Comment (anvit) [reply test/phpunit/QubitFlatfileExportTest.php:336]: Thank you, this is perfect!

**Review by anvit — APPROVED** [review]
